import { Link } from "react-router-dom"
import { ArrowLeftIcon } from "@heroicons/react/24/outline"
import { Tooltip as ReactTooltip } from "react-tooltip"
import FooterMark from "../../components/FooterMark"

export default function TermsOfService() {
  return (
    <div className="flex flex-col w-full h-full">
      <header className="flex w-full justify-center border-b border-gray-200 dark:border-gray-800  shadow-md mb-1">
        <div className="flex mt-8 w-full max-w-full sm:max-w-xl md:max-w-2xl lg:max-w-4xl xl:max-w-5xl 2xl:max-w-6xl mx-2 justify-between items-center">
          <div className="flex gap-2 items-center">
            {/* Go to Help Home */}
            <Link
              to="/help"
              className="m-2 p-2 rounded-full hover:invert dark:hover:invert-0 hover:bg-gray-300 dark:hover:bg-gray-600"
              data-tooltip-id="back-to-home"
            >
              <ArrowLeftIcon className="h-4 w-4" aria-hidden="true" />
            </Link>
            <ReactTooltip
              id="back-to-home"
              place="left"
              content="Back to Help Home"
            />

            <img
              className="h-6 w-6 invert dark:invert-0"
              src="/assets/icons/terms.svg"
              alt="Icon"
            />
            <span className="ml-2 text-2xl font-bold">Terms of Service</span>
          </div>
        </div>
      </header>

      <div className="flex-1 h-full w-full overflow-y-auto p-4">
        <div className="flex flex-col max-w-full sm:max-w-2xl md:max-w-3xl lg:max-w-4xl xl:max-w-5xl 2xl:max-w-5xl mx-auto">
          <p>
            Please read these Terms of Use ("Terms") carefully before using the
            SANAI application ("App"). These Terms govern your access to and use
            of the App, including any content, functionality, and services
            provided through the App.
          </p>
          <ol className="list-decimal ml-5">
            <li>
              <h3 className="font-semibold mt-4">Acceptance of Terms</h3>
              <p>
                By downloading, installing, or using the SANAI App, you agree to
                be bound by these Terms and our Privacy Policy. If you do not
                agree with any part of these Terms, please refrain from using
                the App.
              </p>
            </li>
            <li>
              <h3 className="font-semibold mt-4">User Eligibility</h3>
              <p>
                You must be at least 18 years old or have reached the age of
                majority in your jurisdiction to use the App. By using the App,
                you represent and warrant that you meet these age requirements.
              </p>
            </li>
            <li>
              <h3 className="font-semibold mt-4">Nature of the App</h3>
              <p>
                The SANAI App is an artificial intelligence-powered chat
                application that provides automated responses and conversations.
                Please note that the responses generated by the App may not
                always be accurate or appropriate. The App is not intended to
                replace professional advice or human interaction.
              </p>
            </li>
            <li>
              <h3 className="font-semibold mt-4">User Conduct</h3>
              <p>When using the SANAI App, you agree to:</p>
              <ol className="list-disc ml-6">
                <li>
                  Use the App for lawful purposes only and not engage in any
                  illegal activities.
                </li>
                <li>
                  Respect the intellectual property rights of others and not
                  infringe upon them.
                </li>
                <li>
                  Refrain from transmitting any harmful or malicious code to the
                  App.
                </li>
                <li>
                  Not attempt to access or interfere with the App's underlying
                  systems or security measures.
                </li>
                <li>
                  Use the App responsibly and not engage in any activity that
                  may disrupt or hinder its operation.
                </li>
              </ol>
            </li>
            <li>
              <h3 className="font-semibold mt-4">Privacy</h3>
              <p>
                We are committed to protecting your privacy. Our Privacy Policy
                explains how we collect, use, and disclose information from
                users of the App. By using the App, you consent to our
                collection and use of personal information as outlined in the
                Privacy Policy.
              </p>
            </li>
            <li>
              <h3 className="font-semibold mt-4">Disclaimer of Liability</h3>
              <p>
                The SANAI App is provided on an "as is" and "as available"
                basis. We do not warrant the accuracy, completeness, or
                reliability of the App's responses or content. Your use of the
                App is at your own risk, and we disclaim all liabilities arising
                from any reliance on the App or its responses.
              </p>
            </li>
            <li>
              <h3 className="font-semibold mt-4">Limitation of Liability</h3>
              <p>
                To the extent permitted by law, we shall not be liable for any
                indirect, incidental, special, consequential, or punitive
                damages arising out of or in connection with the use of the App
                or these Terms, even if we have been advised of the possibility
                of such damages. In no event shall our total liability exceed
                the amount you paid, if any, for accessing the App.
              </p>
            </li>
            <li>
              <h3 className="font-semibold mt-4">Intellectual Property</h3>
              <p>
                The App and all its content, including but not limited to text,
                graphics, logos, images, and software, are the property of SANAI
                or its licensors and are protected by intellectual property
                laws. You agree not to modify, distribute, reproduce, or create
                derivative works based on the App or its content without our
                prior written consent.
              </p>
            </li>
            <li>
              <h3 className="font-semibold mt-4">
                Modification and Termination
              </h3>
              <p>
                We reserve the right to modify or terminate the App or these
                Terms at any time, for any reason, without prior notice. You are
                responsible for regularly reviewing the most current version of
                these Terms. Your continued use of the App after any
                modifications to the Terms constitutes acceptance of such
                changes.
              </p>
            </li>
            <li>
              <h3 className="font-semibold mt-4">
                Governing Law and Jurisdiction
              </h3>
              <p>
                These Terms shall be governed by and construed in accordance
                with the laws of [Jurisdiction]. Any disputes arising out of or
                in connection with these Terms shall be subject to the exclusive
                jurisdiction of the courts of [Jurisdiction].
              </p>
            </li>
          </ol>
          <p>
            By using the SANAI App, you acknowledge that you have read,
            understood, and agreed to these Terms.
          </p>
        </div>
        <FooterMark />
      </div>
    </div>
  )
}
